version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: happycareer-db
    environment:
      POSTGRES_DB: happycareer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - happycareer-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: happycareer-redis
    ports:
      - "6379:6379"
    networks:
      - happycareer-network

  # Backend API
  backend:
    build: ./backend
    container_name: happycareer-backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/happycareer
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_EXPIRES_IN: 7d
      PORT: 4000
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
      REDIS_URL: redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    networks:
      - happycareer-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Frontend
  frontend:
    build: ./frontend
    container_name: happycareer-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
      NEXT_PUBLIC_MOONSHOT_API_KEY: ${NEXT_PUBLIC_MOONSHOT_API_KEY}
      NEXT_PUBLIC_REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - happycareer-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_data:

networks:
  happycareer-network:
    driver: bridge
