version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: happycareer-db
    environment:
      POSTGRES_DB: happycareer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - happycareer-network

  backend:
    build: .
    container_name: happycareer-backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/happycareer
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_EXPIRES_IN: 7d
      PORT: 4000
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - happycareer-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:

networks:
  happycareer-network:
    driver: bridge 